services:
  db:
    image: groonga/pgroonga:latest-alpine-16
    volumes:
      - psgl_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '20070920'
    ports:
      - '5432:5432'
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - .:/nyasocom_sun_pg_win
      - public:/nyasocom_sun_pg_win/public
      - tmp:/nyasocom_sun_pg_win/tmp
    environment:
      - POSTGRES_HOST=db
    tty: true
    stdin_open: true
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./secret:/etc/nginx/secret
      - public:/nyasocom_sun_pg_win/public
      - tmp:/nyasocom_sun_pg_win/tmp
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
volumes:
  psgl_data:
    driver: local
  tmp:
  public:
