name: Rails CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
        pgroonga:
          image: groonga/pgroonga:latest-alpine-16
          ports:
            - '5432:5432'
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.6'
      env:
        RAILS_ENV: develop
        POSTGRES_HOST: postgres
        RAILS_DATABASE_USER: postgres
        RAILS_DATABASE_PASSWORD: password

    - name: Cache Ruby gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle # キャッシュするディレクトリを指定します。
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
      
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        gem install bundler
        bundle install
    
    - name: Run Migration
      run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails db:seed
  
    - name: Run RSpec
      run: bundle exec rspec
